### ISSUE TITLE
Reproducing the results

### ISSUE THREAD

**Issue by deepankarvarma** [sharinka0715/InI-Model-Stealing-Defense#1]
Hi, could you please share the default loss parameters (beta,gamma,delta, epsilon) for the results reported in the paper. Sharing a sample config.yaml will help.

Thank you.

**Comment by sharinka0715** [comment]
Hi,

The `config.yaml` of our experiments is generated by `yaml_all.py`. This script will produce a YAML file with default parameters. 
The default parameters in our paper can be found in `run.sh`, and you can get a sample config.yaml by this shell script.
